version: "3.8"

services:
  fronted:
    image: gcr.io/docker-server/fronted:latest
    container_name: fronted 

  backend:
    image: gcr.io/docker-server/backend:latest
    container_name: backend  
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/testdb
    restart: always
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    container_name: nginx

    ports:
      ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

    restart: always
