name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GCR
        run: |
          echo ${{ secrets.GCP_SERVICE_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/docker-server/app:latest .

      - name: Push Image
        run: |
          docker push gcr.io/docker-server/app:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_SSH_HOST }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            docker pull gcr.io/docker-server/app:latest
            docker-compose down
            docker-compose up -d
