name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write   # 🔥 REQUIRED


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 🔐 Authenticate using Workload Identity
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/943086588341/locations/global/workloadIdentityPools/docker-server-git/providers/github
          service_account: github-cicd@project-57b481f9-2513-4a16-ae4.iam.gserviceaccount.com

      # 🛠 Setup gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 🔑 Configure Docker auth
      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      # 🐳 Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/project-57b481f9-2513-4a16-ae4/app:latest .

      # 📤 Push Image
      - name: Push Image
        run: |
          docker push gcr.io/project-57b481f9-2513-4a16-ae4/app:latest

      # 🚀 Deploy to VM (same as your setup)
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_SSH_HOST }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            docker pull gcr.io/project-57b481f9-2513-4a16-ae4/app:latest
            docker-compose down
            docker-compose up -d